# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "Ubuntu Precise 64 (12.04.2) Vanilla"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
   config.vm.network :private_network, ip: "192.168.10.13"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

# Set up hostname & domainname for server (fast2web.lab.belgium.be)
config.vm.provision :shell, :path => "scripts/configure_host.sh"
# Install required packages (including adding MariaDB apt-source)
config.vm.provision :shell, :path => "scripts/add_packages.sh"
# Secure MariaDB
config.vm.provision :shell, :path => "scripts/secure_mysql.sh"
# Configure PHP5-FPM
config.vm.provision :shell, :path => "scripts/configure_php.sh"
# Configure Apache
config.vm.provision :shell, :path => "scripts/configure_apache.sh"
# Add Fedict user
config.vm.provision :shell, :path => "scripts/add_fedict_user.sh"
# Add Fedict user to mysql
config.vm.provision :shell, :path => "scripts/add_fedict_user_mysql.sh"
# Set up subdir structure for fast2web under /home/fedict
config.vm.provision :shell, :path => "scripts/add_web_structure.sh"
# Install Drush and initialise .drush for fedict user
config.vm.provision :shell, :path => "scripts/configure_drush.sh"
# Set up Fast2Web platform as Fedict user
config.vm.provision :shell, :inline => "sudo -H -u fedict /vagrant/scripts/add_openfed.sh"

end
